import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/toolkit/ReduxProvider";
import Protected from "@/components/protectedRoute/Protected";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ReduxProvider><Protected>{children}</Protected></ReduxProvider>
      </body>
    </html>
  );
}
